{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pm3-microservices
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
{{- range $name, $svc := .Values.services }}
          - path: {{ $svc.ingressPath }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $svc.port }}
{{- end }}
{{- end }}
