apiVersion: v1
kind: ConfigMap
metadata:
  name: team3-config
  namespace: {{ .Values.namespace }}
data:
  KAFKA_BROKERS: {{ .Values.config.kafkaBrokers | quote }}
  KAFKA_CONFIG_TOPIC: "config.updated"
  KAFKA_FLAG_TOPIC: "flag.updated"
  KAFKA_THRESHOLD_TOPIC: "metrics.threshold.exceeded"
  KAFKA_NOTIFICATION_SENT_TOPIC: "notification.sent"
  KAFKA_UPLOAD_COMPLETED_TOPIC: "upload.completed"
  KAFKA_REPLICATION_COMPLETED_TOPIC: "replication.completed"
  KAFKA_QUOTA_EXCEEDED_TOPIC: "quota.exceeded"
  KAFKA_BACKUP_COMPLETED_TOPIC: "backup.completed"
  KAFKA_METRICS_THRESHOLD_TOPIC: "metrics.threshold.exceeded"
  DEFAULT_THRESHOLD: {{ .Values.config.defaultThreshold | quote }}
  ENABLE_THRESHOLD_ALERTS: {{ .Values.config.alertsEnabled | quote }}
  DEFAULT_RECIPIENT: {{ .Values.config.defaultRecipient | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otelExporterOtlpEndpoint | quote }}
