apiVersion: v1
kind: Secret
metadata:
  name: team3-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  METRICS_DATABASE_URL: {{ .Values.secrets.metricsDatabaseUrl | quote }}
  NOTIFICATION_DATABASE_URL: {{ .Values.secrets.notificationDatabaseUrl | quote }}
