apiVersion: v1
kind: ConfigMap
metadata:
  name: team3-config
  namespace: cse474-prod
data:
  KAFKA_BROKERS: kafka:9092
  KAFKA_CONFIG_TOPIC: config.updated
  KAFKA_FLAG_TOPIC: flag.updated
  KAFKA_THRESHOLD_TOPIC: metrics.threshold.exceeded
  KAFKA_NOTIFICATION_SENT_TOPIC: notification.sent
  KAFKA_UPLOAD_COMPLETED_TOPIC: upload.completed
  KAFKA_REPLICATION_COMPLETED_TOPIC: replication.completed
  KAFKA_QUOTA_EXCEEDED_TOPIC: quota.exceeded
  KAFKA_BACKUP_COMPLETED_TOPIC: backup.completed
  KAFKA_METRICS_THRESHOLD_TOPIC: metrics.threshold.exceeded
  DEFAULT_THRESHOLD: "80"
  ENABLE_THRESHOLD_ALERTS: "true"
  DEFAULT_RECIPIENT: ops@example.com
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger-collector.cse474-prod.svc.cluster.local:4318
