apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-service-config
  namespace: cse474-prod
data:
  NODE_ENV: "development"
  SERVICE_NAME: "metrics-service"
  PORT: "3001"
  OTEL_TRACING_ENABLED: "true"
  OTEL_SERVICE_NAME: "metrics-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318/v1/traces"
  METRICS_SERVICE_URL: "http://metrics-service:3001"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3002"
  PREVIEW_SERVICE_URL: "http://preview-service:3003"
  COMPRESSION_SERVICE_URL: "http://compression-service:3004"
  WEBHOOK_SERVICE_URL: "http://webhook-service:3005"
  SCHEDULER_SERVICE_URL: "http://scheduler-service:3006"
  ACCESS_ANALYTICS_SERVICE_URL: "http://access-analytics-service:3007"
  BACKUP_SERVICE_URL: "http://backup-service:3008"
