apiVersion: v1
kind: Secret
metadata:
  name: team3-secrets
  namespace: cse474-prod
type: Opaque
stringData:
  METRICS_DATABASE_URL: postgresql://postgres:postgres@metrics-db:5432/metrics_service
  NOTIFICATION_DATABASE_URL: postgresql://postgres:postgres@notification-db:5432/notification_service
