apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgres.password | default "password" | b64enc | quote }}
  JWT_SECRET: {{ "supersecret" | b64enc | quote }}
