apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.audit.name }}-config
  namespace: {{ .Values.namespace }}
data:
  PORT: {{ .Values.audit.service.port | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318/v1/traces"
  KAFKA_BROKER: {{ .Values.kafka.broker | quote }}
